@startuml

title __QLLSIM's Class Diagram__\n

  namespace com.uwaterloo.iqc.qllsim {
    class com.uwaterloo.iqc.qllsim.KeyGenPeer {
        {static} + main()
    }
    class com.uwaterloo.iqc.qllsim.KeyGenPeerActor {
        {static} ~ fileCnt : long
        ~ home : String
        ~ ip : String
        ~ outputLocation : String
        ~ outputSz : long
        ~ port : long
        ~ rng : SecureRandom
        ~ rngPeer : SecureRandom
        ~ seed : String
        ~ seedPeer : String
        ~ selectionString : String
        ~ siteId : String
        - cfg : Config
        - selection : ActorSelection
        + KeyGenPeerActor()
        + onReceive(message: Object) <@Override>
        - generateKeys(location: String, random: SecureRandom )
    }
    class com.uwaterloo.iqc.qllsim.Messages {
    }
    class com.uwaterloo.iqc.qllsim.Messages.KeyGenReq {
        {static} - serialVersionUID : long
        - siteId : String
        + KeyGenReq(id:String)
        + getId()
    }
    class com.uwaterloo.iqc.qllsim.Messages.KeyGenResp {
        - cnt : long
        - digest : String
        {static} - serialVersionUID : long
        - siteId : String
        + KeyGenResp(siteId:String, digest:String, cnt:long)
        + getCnt()
        + getDigest()
        + getId()
    }
  }
  

  com.uwaterloo.iqc.qllsim.Messages +-down- com.uwaterloo.iqc.qllsim.Messages.KeyGenReq
  com.uwaterloo.iqc.qllsim.Messages +-down- com.uwaterloo.iqc.qllsim.Messages.KeyGenResp
  com.uwaterloo.iqc.qllsim.Messages.KeyGenReq .up.|> Serializable
  com.uwaterloo.iqc.qllsim.Messages.KeyGenResp .up.|> Serializable
  com.uwaterloo.iqc.qllsim.KeyGenPeer ..> com.uwaterloo.iqc.qllsim.KeyGenPeerActor : uses
  com.uwaterloo.iqc.qllsim.KeyGenPeer ..> akka.actor.ActorRef : uses
  com.uwaterloo.iqc.qllsim.KeyGenPeer ..> akka.actor.ActorSystem : uses
  com.uwaterloo.iqc.qllsim.KeyGenPeerActor ..> com.uwaterloo.iqc.qllsim.Messages.KeyGenReq : uses
  com.uwaterloo.iqc.qllsim.KeyGenPeerActor ..> com.uwaterloo.iqc.qllsim.Messages.KeyGenResp : uses
  com.uwaterloo.iqc.qllsim.KeyGenPeerActor --|> akka.actor.UntypedAbstractActor


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
